;; *************** macroList.asm ***************
;; MacroList export. Friday, August 2, 2024 10:08:50 PM

  .include ROOT\System\Macros\AddValue.asm
  .include ROOT\System\Macros\ChangeActionStep.asm
  .include ROOT\System\Macros\ChangeFacingDirection.asm
  .include ROOT\System\Macros\ChangeTileAtCollision.asm
  .include ROOT\System\Macros\CheckCollisionPoint.asm
  .include ROOT\System\Macros\Compare16.asm
  .include ROOT\System\Macros\CountObjects.asm
  .include ROOT\System\Macros\CreateObject.asm
  .include ROOT\System\Macros\CreateObjectOnScreen.asm
  .include ROOT\System\Macros\DestroyObject.asm
  .include ROOT\System\Macros\DoObjectAction.asm
  .include ROOT\System\Macros\DrawBox.asm
  .include ROOT\System\Macros\DrawHud.asm
  .include ROOT\System\Macros\DrawNumber.asm
  .include ROOT\System\Macros\DrawSprite.asm
  .include ROOT\System\Macros\DrawSpriteHud.asm
  .include ROOT\System\Macros\DrawText.asm
  .include ROOT\System\Macros\DrawTextDirect.asm
  .include ROOT\System\Macros\DrawTilesDirect.asm
  .include ROOT\System\Macros\DrawVariableTiles.asm
  .include ROOT\System\Macros\EraseBox.asm
  .include ROOT\System\Macros\GetActionStep.asm
  .include ROOT\System\Macros\GetCollisionPoint.asm
  .include ROOT\System\Macros\GetObjectDirection.asm
  .include ROOT\System\Macros\GetTrigger.asm
  .include ROOT\System\Macros\HideHud.asm
  .include ROOT\System\Macros\HideSprites.asm
  .include ROOT\System\Macros\LoadAttributeData.asm
  .include ROOT\System\Macros\LoadBackgroundPalettes.asm
  .include ROOT\System\Macros\LoadChrData.asm
  .include ROOT\System\Macros\LoadCollisionData.asm
  .include ROOT\System\Macros\LoadCollisionData2.asm
  .include ROOT\System\Macros\LoadNametableData.asm
  .include ROOT\System\Macros\LoadNametableDataFull.asm
  .include ROOT\System\Macros\LoadObjectPalettes.asm
  .include ROOT\System\Macros\LoadObjectSubPalettes.asm
  .include ROOT\System\Macros\LoadScreenTableData.asm
  .include ROOT\System\Macros\MoveTowardsPoint.asm
  .include ROOT\System\Macros\PlaySong.asm
  .include ROOT\System\Macros\PlaySound.asm
  .include ROOT\System\Macros\QueueText.asm
  .include ROOT\System\Macros\ReturnBank.asm
  .include ROOT\System\Macros\ShowHud.asm
  .include ROOT\System\Macros\ShowSprites.asm
  .include ROOT\System\Macros\StartMoving.asm
  .include ROOT\System\Macros\StopMoving.asm
  .include ROOT\System\Macros\StopSound.asm
  .include ROOT\System\Macros\SubtractValue.asm
  .include ROOT\System\Macros\SwitchBank.asm
  .include ROOT\System\Macros\TriggerScreen.asm
  .include ROOT\System\Macros\UpdateHudElement.asm
  .include ROOT\System\Macros\UpdatePosition.asm
  .include ROOT\System\Macros\WarpToScreen.asm
