;; *************** ObjectStatusPointers.asm ***************
;; Object Pointers export. Thursday, September 19, 2024 7:22:47 PM

CREATE_STATE_POINTER_LO: 
CREATE_STATE_POINTER_HI: 
INPUT_STATE_POINTER_LO : 
INPUT_STATE_POINTER_HI : 
UPDATE_STATE_POINTER_LO : 
UPDATE_STATE_POINTER_HI : 
DRAW_STATE_POINTER_LO : 
DRAW_STATE_POINTER_HI : 
TILE_COLLISION_STATE_POINTER_LO : 
TILE_COLLISION_STATE_POINTER_HI : 
OBJECT_COLLISION_STATE_POINER_LO  : 
OBJECT_COLLISION_STATE_POINER_HI  : 
BOUNDS_STATE_POINTER_LO  : 
BOUNDS_STATE_POINTER_HI  : 
TIMER_STATE_POINTER_LO : 
TIMER_STATE_POINTER_HI : 
DESTROY_STATE_POINTER_LO  : 
DESTROY_STATE_POINTER_HI  : 
