;; *************** UserDefinedConstants.asm ***************
;; UserDefinedConstants export. Thursday, September 19, 2024 7:17:21 PM

OBJECT_OBSERVES_INPUT  = $20
OBJECT_OBSERVES_PHYSICS  = $10
OBJECT_OBSERVES_TILES  = $08
OBJECT_OBSERVES_OBJECTS  = $04
OBJECT_OBSERVES_DRAWING  = $02
OBJECT_QUEUED_FOR_ACTIVATION  = $40
OBJECT_IS_ACTIVE  = $80
OBJECT_QUEUED_FOR_DESTRUCTION  = $01
SCROLL_SPEED_LO  = $50
SCROLL_SPEED_HI  = $01
SCROLL_BORDER_R  = $90
SCROLL_BORDER_L  = $70
SCROLL_BORDER_U  = $64
SCROLL_BORDER_D  = $8c
GS_MainGame  = $00
GS_StartScreen  = $00
HUD_OFFSET  = $c0
TEXT_MORE_INDICATOR  = $00
HUD_BANK  = $1e
