
	.include SCR_CHANGE_AI_STEP
	.include SCR_CHANGE_ANIMATION_STEP
	.include SCR_CHANGE_ATTRIBUTE
	.include SCR_CHANGE_BACKGROUND_PALETTE
	.include SCR_CHANGE_BACKGROUND_TILE
	;.include SCR_CHANGE_FACING_DIRECTION
	.include SCR_CHANGE_GAME_STATE
	.include SCR_CHANGE_GAME_SUB_STATE
	.include SCR_CHANGE_GRAVITY
	.include SCR_CHANGE_SPEED
	.include SCR_CHANGE_SPRITE_PRIORITY
	.include SCR_CHANGE_SPRITE_PALETTE
	.include SCR_CHANGE_SUBPALETTE
	.include SCR_CHECK_GLOBAL_VARIABLE
	.include SCR_CHECK_LOCAL_VARIABLE
	.include SCR_CREATE_OBJECT
	.include SCR_DESTROY_CURRENT_OBJECT
	.include SCR_DESTROY_SELECTED_OBJECT
	.include SCR_DRAW_SPRITE
	.include SCR_FLIP_AI_BITS
	.include SCR_MOVE_TOWARDS_OBJECT
	.include SCR_MOVE_TOWARES_POSITION
	.include SCR_NO_BEHAVIOR
	.include SCR_OPEN_BOX
	.include SCR_PLAY_MUSIC
	.include SCR_PLAY_SFX
	.include SCR_REVERSE_DIRECTION
	.include SCR_RUN_CODE
	.include SCR_RUN_SUBROUTINE
	.include SCR_SET_GLOBAL_VARIABLE
	.include SCR_SET_LOCAL_VARIABLE
	;.include SCR_START_MOVING
	.include SCR_STOP_SOUNDS
	;.include SCR_STOP_MOVING
	.include SCR_UPDATE_HUD
	;.include SCR_UPDATE_POSITION
	
Object_Behavior_Offset_table:





;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;; OLD BEHAVIOR METHOD
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
